### ISSUE TITLE
Downloading videos from Impartus Platform

### ISSUE THREAD

**Issue by shaksham95** [iamkroot/ilc-scraper#10]
Hey @iamkroot ,

I was wondering if it's possible to download videos from [Impartus](http://a.impartus.com/) directly. 

I tried doing this, but it failed since it assumes that the URL is of the format "172.16.3.20/....." which is applicable for on-campus students. Is it possible to download the videos from off-campus? It would be a big help if you can provide some pointers

Thanks
Shaksham

**Comment by iamkroot** [comment]
It works already.
Example: `http://a.impartus.com/...`

**Comment by shaksham95** [comment]
It isn't working for me. I am trying to download a video from Impartus and it's giving the following error:

![image](https://user-images.githubusercontent.com/7498849/77824106-07b1a500-7126-11ea-9276-4390dbd19109.png)

I have downloaded the exe file for windows which is published under the "Releases". The URL that I am trying to retrieve is http://a.impartus.com/ilc/#/video/id/1840519

I would really appreciate if you can provide an example of how can I download the video.

Thanks

**Comment by iamkroot** [comment]
You're supposed to specify the link to the course, not to a specific video.

**Comment by shaksham95** [comment]
Hey,

So after passing the URL (as you mentioned) to the scrapper, I am getting the following error:-

![image](https://user-images.githubusercontent.com/7498849/78441238-a04fa400-7695-11ea-9c12-d4df0a4e38e4.png)

**Comment by iamkroot** [comment]
Update.

**Comment by shaksham95** [comment]
Hey @iamkroot ,

I have tried using the updated scrapper (version 0.6.2 and 0.6.1) but the error is still the same as shown in the screenshot above. Anything that I might be missing?

**Comment by iamkroot** [comment]
course url?

**Comment by shaksham95** [comment]
Course URL: https://a.impartus.com/ilc/#/course/160200/706

**Comment by iamkroot** [comment]
Are you sure you have the right url? I don't see _anything_ when I open
that link, just a blank page.

**Comment by shaksham95** [comment]
Yes, attaching a screenshot of the URL page:

![image](https://user-images.githubusercontent.com/7498849/78450750-764eaf80-769e-11ea-9674-ade63200b536.png)

**Comment by iamkroot** [comment]
Must be cuz you're from Pilani. Well, I can't find the reason for the bug
since I don't have access to the data.

**Comment by shaksham95** [comment]
Is the software dependent on the BITS campus? It considers the course URL, then ideally it should download the content.

It looks like the code is not be able to access the course page; that's why no videos are coming in the list resulting in NoneType error.

**Comment by sundrb** [comment]
> Hey,
> 
> So after passing the URL (as you mentioned) to the scrapper, I am getting the following error:-
> 
> ![image](https://user-images.githubusercontent.com/7498849/78441238-a04fa400-7695-11ea-9c12-d4df0a4e38e4.png)

I have the same issue... What needs to be done to rectify?

**Comment by shaksham95** [comment]
There is no workaround for this issue.
