### ISSUE TITLE
Problems using the scrapper..

### ISSUE THREAD

**Issue by Salphaella** [iamkroot/ilc-scraper#11]
Hey, I was excited to see this scrapper for Impartus but I ran into some issues while attempting to use it. I've attached a log into the errors that were run into from the status 
[Impartusscrapperlog.txt](https://github.com/iamkroot/ilc-scraper/files/4400946/Impartusscrapperlog.txt)

I hope this issue can be resolved.

**Comment by iamkroot** [comment]
Use `http`, not `https`
