### ISSUE TITLE
Further errors

### ISSUE THREAD

**Issue by Salphaella** [iamkroot/ilc-scraper#12]
Using http rather than https seems to have helped things, but still running into some errors...

>  Couldn't find C:\Users\Al\Downloads\imp_config.json. Will skip for now.
> Saving to "C:\Users\Al\Downloads\Impartus Lectures\UE18BC221-Linux Administration Jan - May 2020 RR"
> Downloading lecture numbers: 1 2 3 4 5 6 7 8
> Traceback (most recent call last):
>   File "ilc_scrape.py", line 338, in <module>
>   File "ilc_scrape.py", line 328, in main
>   File "multiprocessing\pool.py", line 276, in starmap
>   File "multiprocessing\pool.py", line 657, in get
>   File "multiprocessing\pool.py", line 121, in worker
>   File "multiprocessing\pool.py", line 47, in starmapstar
>   File "downloader.py", line 166, in download_stream
>   File "downloader.py", line 134, in add_inputs
> TypeError: sequence item 0: expected str instance, int found
> Processing 01. lvm 2020-03-18.mkv
> Processing 03. lvm demonstration 2020-03-23.mkv
> Processing 05. Unit 5 Linux Boot ProcessUnit 5 Linux Boot Process 2020-03-26.mkv
> Processing 07. Unit 5 Boot Process 2020-03-28.mkv
> <class 'TypeError'> sequence item 0: expected str instance, int found <traceback object at 0x000001DB5BDFB348>

**Comment by Salphaella** [comment]
Is the issue on my end?

> Couldn't find C:\Users\Al\Downloads\imp_config.json. Will skip for now.
> Traceback (most recent call last):
>   File "ilc_scrape.py", line 338, in <module>
>   File "ilc_scrape.py", line 258, in main
>   File "ilc_scrape.py", line 204, in login
> KeyError: 'message'

**Comment by iamkroot** [comment]
@Salphaella create a new issue

**Comment by Salphaella** [comment]
Oh alright
