### ISSUE TITLE
KeyError: 'message'

### ISSUE THREAD

**Issue by Salphaella** [iamkroot/ilc-scraper#14]
> Couldn't find C:\Users\Al\Downloads\imp_config.json. Will skip for now.
> Traceback (most recent call last):
>   File "ilc_scrape.py", line 338, in <module>
>   File "ilc_scrape.py", line 258, in main
>   File "ilc_scrape.py", line 204, in login
> KeyError: 'message'

**Comment by iamkroot** [comment]
Please provide a proper bug report, which follows the given template.
