### ISSUE TITLE
"TypeError" in get_angle_playlists

### ISSUE THREAD

**Issue by dharmrajsharma16** [iamkroot/ilc-scraper#19]
**Context**
* OS: Windows 10
* Install method: EXE
* Your location: Outside Campus
* Course URL: https://a.impartus.com/ilc/#/course/160200/706
* Lecture range: 4:9
**Additional context**
NA

**Describe the bug**
Encountered with "TypeError" exception while trying to download the lectures.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/16904755/79263633-d3254380-7eb0-11ea-8662-ad84aaff1141.png)
![image](https://user-images.githubusercontent.com/16904755/79263727-fd770100-7eb0-11ea-89aa-66e724ff0c1b.png)
![image](https://user-images.githubusercontent.com/16904755/79263782-17184880-7eb1-11ea-93cb-fc42f02b48d6.png)
![image](https://user-images.githubusercontent.com/16904755/79263914-4cbd3180-7eb1-11ea-98a9-6d7cb4d7b6dc.png)

**Program output**
<details>
<summary>Click to see output</summary>
<p>

```
Saving to "C:\ImpartusLacture\Python Fundamentals for Data Science (S2-19_DSECLPFDS) 2019-20 Sem 2"
Downloading lecture numbers: 4 5 6 7 8
Traceback (most recent call last):
  File "ilc_scrape.py", line 345, in <module>
  File "ilc_scrape.py", line 335, in main
  File "multiprocessing\pool.py", line 276, in starmap
  File "multiprocessing\pool.py", line 657, in get
  File "multiprocessing\pool.py", line 121, in worker
  File "multiprocessing\pool.py", line 47, in starmapstar
  File "downloader.py", line 167, in download_stream
  File "downloader.py", line 104, in get_angle_playlists
TypeError: list indices must be integers or slices, not NoneType
Processing 04. Orientation-M.Tech In Dse Online Cluster 2020-03-28.mkv
Processing 06. Python-2 2020-04-05.mkv
Processing 08. Python Fundamentals For Data Science Part 4 2020-04-12.mkv
<class 'TypeError'> list indices must be integers or slices, not NoneType <traceback object at 0x000002681B153F88>

```
</p>
</details>

**Comment by dharmrajsharma16** [comment]
Course Page
![image](https://user-images.githubusercontent.com/16904755/79265599-fac9db00-7eb3-11ea-9768-8977f0e238b4.png)

**Comment by iamkroot** [comment]
As I said in #10, this seems to a Pilani specific issue, due to how cameras have been set up there. I don't have access to the lectures, and so I can't fix this. If someone else wants to do so, they're welcome to make a proper PR with a fix.

**Comment by shaksham95** [comment]
@iamkroot Can you help me in figuring this out? I have been trying to poke around your code and the error which I mentioned in #10 is present below with more information:

![image](https://user-images.githubusercontent.com/7498849/80066700-0ffcd480-855a-11ea-9c7a-60f6dd4c6b75.png)

As you can see, I am only passing the option to capture `" left" camera angle` and what is happening in `get_angle_playlists` is that a `None` value is getting returned when you execute the following line `last_key = find_startswith(angle1, "#EXT-X-KEY", rev=True)`.

For your reference, in the output, you can see the values of the following variables: `angle1_end`, `angle`, and `last_key`.

Do let me know if you can figure out now what might be going wrong? Also, in the output, I don't see the download link for the video? Where can I find that?

**Comment by sundrb** [comment]
@iamkroot , @shaksham95 Solving this issue should help us lot.
Please do consider what should be done to resolve the issue. Please let me know what support I can give you.

**Comment by iamkroot** [comment]
To debug, I'll need to see the m3u8 playlist file for the lecture. If you have setup using the manual method, open downloader.py and add
```
with open("playlist.m3u8", "w") as f:
    f.write(variant_pls)
```
after line 165, before the invocation of `get_angle_playlists` function. Then save it and run it again. This ought to store the file on your computer. Attach it here.

**Comment by iamkroot** [comment]
PS: @shaksham95 your password is visible in the screenshot.

**Comment by sundrb** [comment]
I think I understood and did correctly.
Added the code u said.
![image](https://user-images.githubusercontent.com/55596936/80308214-3e451300-87eb-11ea-898e-f040d3cca19b.png)
But, No action on sceen
![image](https://user-images.githubusercontent.com/55596936/80308237-62a0ef80-87eb-11ea-8a6d-33dff4e64c05.png)

**Comment by shaksham95** [comment]
@iamkroot I have the file as you requested, but I can't upload here since there's a restriction on the type of file that can be uploaded. 

The file has 6 hours of footage with the video running in chunks, it seems.

**Comment by iamkroot** [comment]
@shaksham95 upload it to pastebin then. I need to see the structure of the file.

**Comment by shaksham95** [comment]
@iamkroot I am not sure how to upload a video file on pastebin. Any ideas?

**Comment by iamkroot** [comment]
What video file? I was talking about the m3u8 file that would've been
saved. It's a text file, not video.

**Comment by shaksham95** [comment]
@iamkroot  Okay, the code which you shared the output for it is coming to a video (m3u8) file. It's a file running videos in chunks. I suppose you are asking for the text input which I have attached here, let me know if this is what you need.

[playlist.txt](https://github.com/iamkroot/ilc-scraper/files/4537603/playlist.txt)

**Comment by sundrb** [comment]
Thanks @iamkroot & @shaksham95 for working on it :)

**Comment by iamkroot** [comment]
Ok I had a look through that playlist file and it seems that these are very different from the pre-recorded streams we get. The video stream is unencrypted, and can be downloaded even without logging into impartus.

**Comment by iamkroot** [comment]
@shaksham95 I've pushed a possible fix in the [`pilani-live`](https://github.com/iamkroot/ilc-scraper/tree/pilani-live) branch. Clone that and try to run the scraper again (using cmd line). See if its working (wait for the entire vid to be downloaded).

**Comment by shaksham95** [comment]
Okay, I tried it out and now getting the following error;

![image](https://user-images.githubusercontent.com/7498849/80360943-bec44c00-889d-11ea-91e0-59a52408c914.png)

**Comment by iamkroot** [comment]
@shaksham95 updated, try now

**Comment by shaksham95** [comment]
@iamkroot Okay, I tried that out and the videos are now downloading, thanks a lot for your time. 

However, the lectures are of 2-2.30 hrs but the video footage is usually of 5-6 hrs, the same video is repeated twice, any idea what might be causing that?

**Comment by sundrb** [comment]
Dear @iamkroot & @shaksham95, thanks a lot for your time and efforts...

@iamkroot, Can we try through [release](url) because, i am using office laptop and cannot define environment variables for ffmpeg for executing python.

**Comment by iamkroot** [comment]
> any idea what might be causing that?

No clue, impartus shenanigans.

I can't add any more specific stuff, because it will have to be hardcoded and it will break the normal use case.

> Can we try through [release](url) because

I was waiting for confirmation that it works. A new version will be released soon.

**Comment by shaksham95** [comment]
@iamkroot Okay, no problem. Everything works fine; please release a new version at your earliest convenience. Thanks again for your help :)

**Comment by sundrb** [comment]
> > any idea what might be causing that?
> 
> No clue, impartus shenanigans.
> 
> I can't add any more specific stuff, because it will have to be hardcoded and it will break the normal use case.
> 
> > Can we try through [release](url) because
> 
> I was waiting for confirmation that it works. A new version will be released soon.

Any idea when it will be released? because otherwise Ill try to raise a ticket with  my IT team as it require elevated permission to make changes to environment variables.

**Comment by sundrb** [comment]
New [Release ](https://github.com/iamkroot/ilc-scraper/releases/download/v0.7.0/impartus-scraper-windows.exe) working :)

Also, it will be great if u can support us in downloading all quiz questions in one page. That is much required.
