### ISSUE TITLE
Course URL 

### ISSUE THREAD

**Issue by JeelPatel07** [iamkroot/ilc-scraper#25]
Hey @iamkroot ,

Unable to download videos. Can other campus students use this scraper?. Will it work for them?

URL :-  https://a.impartus.com/ilc#/course/151112/727

error: argument -c/--course_url: URL doesn't match required pattern.

**Comment by iamkroot** [comment]
1) Don't @ me (or anyone) unless important. It's rude.
2) Read the help section in README.
