### ISSUE TITLE
Request to make the tool work for all universities

### ISSUE THREAD

**Issue by hritvikpatel4** [iamkroot/ilc-scraper#26]
I believe that this tool currently works only for BITS Hyderabad, but it would be nice if it would work for PES University and many other colleges that use impartus as their online class platform. I can help to integrate this tool with our college's impartus servers.

**Comment by iamkroot** [comment]
Hey @hritvikpatel4, the major blocker for this is #15. Currently, the URLs of the BITS impartus servers are hardcoded in the initial course URL detection. If we find a nice way to easily handle addition of new server URLs for this, then adding your uni would be trivial.
