### ISSUE TITLE
Handling multiple url

### ISSUE THREAD

**Issue by aayusharyan** [iamkroot/ilc-scraper#31]
**Is your feature request related to a problem? Please describe.**
I have 4 courses in Impartus and every time I want to update my local data with latest video lectures, I have to check the URL from the browser and paste it and start and wait to finish and then get the new one. 🔁 This is frustrating.

**Describe the solution you'd like and other alternatives**
- It'll be so cool if there was a dropdown (which contained all existing pasted URLs).
- Or it allowed `,`, or `:` or some other special character (Since we know the URL structure of impartus, we don't have to care about universality and we can easily define a special character).
- Or, (this is my best so far), we can add a `+` button, clicking on which will add a new text field where we can input the URL for the second course and it will be non versatile data like other fields... So, next time I open the scraper, All I have to do is just click Starrt and it will handle everything.

**Additional context**
I don't think there is any, but if you need some more clarity, please feel free to ask.

**Comment by iamkroot** [comment]
> It'll be so cool if there was a dropdown (which contained all existing pasted URLs).


It already does that. Whenever you use a new url, it is saved in an `imp_data.json` file in the same directory from where it is run. You can click on the course name from drop down the next time onwards. (look at the screenshot in the README)

**Comment by aayusharyan** [comment]
Oh right, got it.
Closing this ticket then.
