### ISSUE TITLE
Not downloading the whole lecture

### ISSUE THREAD

**Issue by shanky1506** [iamkroot/ilc-scraper#6]
Tried downloading a lecture, the GUI indicated it's done downloading and ended with a less than 2 MB file.which has just 20 secs of the lecture, # @

**Comment by iamkroot** [comment]
Could you provide more information? Which lecture (url) are you trying? What exactly does the app say? Are you able to play it on impartus (in case you are subscribed)?

**Comment by shanky1506** [comment]
App says it completed downloading, Yes I am able to play the video in impartus. I tried 2 different videos. but it's not working.
This is the link I used
http://a.impartus.com/api/subjects/115912/lectures/691

**Comment by iamkroot** [comment]
Try with the intranet link: http://172.16.3.20/ilc/#/course/115912/691

In most cases, the problem is with the impartus servers.

**Comment by shanky1506** [comment]
at the end, even with the intranet or internet link API link will be the same right?

**Comment by iamkroot** [comment]
The servers are different, so the api link will be different. You'll have to delete the current link from the imp_data.json file

**Comment by shanky1506** [comment]
Thanks. It is working( Used the intranet Link.)
